on:
  workflow_run:
    workflows: ["Increase version and create tag"]
    types: 
      - completed

name: Create release with notes
jobs:
  create_github_release_with_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set git username and user email
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
      -name: Get latest tag
        run: |
          echo "GIT_LATEST_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.GIT_LATEST_TAG }} --generate-notes
