name: Create Pull Request on merge in main branch

define: &target_branch 'main'

on:
  pull_request:
    types:
      - closed
    branches: 
      - *target_branch

permissions:
  contents: write
  pull-requests: write

jobs:
  create_version_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: *target_branch

      - name: Set git username and user email
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install 
        run: |
          yarn install      

      - name: Turm on git version tagging
        run: |
          yarn config set version-git-tag true

      - name: Make commit for patch
        if: startsWith(github.event.pull_request.title, '[patch]')
        run: |
          yarn version --patch

      - name: Make commit for major changes
        if: startsWith(github.event.pull_request.title, '[major]')
        run: |
          yarn version --major

      - name: Make commit for minor changes
        if: ${{ !startsWith(github.event.pull_request.title, '[patch]') && !startsWith(github.event.pull_request.title, '[major]') }}
        run: |
          yarn version --minor 

      - name: git push repo and tag
        run: |
          git push
          git push --tags

  create_github_release_with_noted:
    runs-on: ubuntu-latest
    needs: create_version_tag
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: *target_branch
      - name: Create release
        run: |
          gh release create ${{ github.ref }} --generate-notes
      
