on:
  workflow_run:
    workflows: ["Increase version and create tag"]
    types: 
      - completed

name: Create release with notes
jobs:
  create_github_release_with_notes:
    if: github.event.workflow_run.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set git username and user email
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Get latest tag
        id: store_latest_tag_in_env
        run: |
          echo "GIT_LATEST_TAG=$(git describe --tags --abbrev=0)"
          echo "GIT_LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      
      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ env.GIT_LATEST_TAG }}"
          gh release create ${{ env.GIT_LATEST_TAG }} --generate-notes
