
on:
  pull_request:
    types:
      - closed
    branches: 
      - main

permissions:
  contents: write
  pull-requests: write

name: Increase version and create tag
jobs:
  create_version_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.TOKEN }}

      - name: Set git username and user email
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install 
        run: |
          yarn install      

      - name: Turm on git version tagging
        run: |
          yarn config set version-git-tag true
          yarn config set version-git-message "%s"
          yarn config set version-tag-prefix ""

      - name: Make commit for patch
        if: startsWith(github.event.pull_request.title, '[patch]')
        run: |
          yarn version --patch

      - name: Make commit for major changes
        if: startsWith(github.event.pull_request.title, '[major]')
        run: |
          yarn version --major

      - name: Make commit for minor changes
        if: ${{ !startsWith(github.event.pull_request.title, '[patch]') && !startsWith(github.event.pull_request.title, '[major]') }}
        run: |
          yarn version --minor 

      - name: git push repo and tag
        run: |
          git push
          git push --tags
